{% set version = "7.2.14" %}

package:
  name: virtuoso-opensource
  version: {{ version }}

source:
  url: https://github.com/openlink/virtuoso-opensource/archive/v{{ version }}.tar.gz
  sha256: 0f1f45fa4ff652f75debcdc81a8f579028177a3f0b7493b0c9b27109b1f1b09a

build:
  number: 0
  skip: true  # [win]

requirements:
  # > from README.md
  # | Package  | Minimum | Upto   |
  # |----------|-------: |------: |
  # | autoconf | 2.57    | 2.69   |
  # | automake | 1.9     | 1.16.1 |
  # | bison    | 2.3     | 3.5.1  |
  # | flex     | 2.5.33  | 2.6.4  |
  # | gawk     | 3.1.1   | 5.3.0  |
  # | gperf    | 3.0.1   | 3.1    |
  # | libtool  | 1.5     | 2.4.6  |
  # | m4       | 1.4.1   | 1.4.18 |
  # | make     | 3.79.1  | 4.2.1  |
  # | openssl  | 0.9.8e  | 3.3.x  |
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - autoconf 2.*
    - automake 1.*
    - bison <3.6
    - flex 2.*
    - gawk <5.1
    - gperf 3.*
    - libtool 2.*
    - m4 1.*
    - make 4.*
  host:
    - openssl
  run:
    - openssl


test:
  commands:
    # virtuoso-t, isql, isqlw, virt_mail, virtuoso-sample-t, inifile
    - isql --help

about:
  home: https://virtuoso.openlinksw.com
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: |
    Virtuoso is a high-performance and scalable Multi-Model RDBMS, Data
    Integration Middleware, Linked Data Deployment, and HTTP Application Server
    Platform
  doc_url: http://vos.openlinksw.com/owiki/wiki/VOS
  dev_url: https://github.com/openlink/virtuoso-opensource

extra:
  recipe-maintainers:
    - bollwyvl
