{% set name = "virtuoso-opensource" %}
{% set version = "7.2.6.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/openlink/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 73dc3d0073d3d5694da075063b75a404649c027a1f5c635a25ede52713ff7942

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    # autoconf	2.57	http://www.gnu.org/software/autoconf/
    - autoconf  # [unix]
    # automake	1.9	http://www.gnu.org/software/automake/
    - automake  # [unix]
    # libtool	1.5	http://www.gnu.org/software/libtool/
    - libtool  # [unix]
    # flex	2.5.33	http://flex.sourceforge.net/
    - flex  # [unix]
    # bison	2.3	http://www.gnu.org/software/bison/
    - bison  # [unix]
    # gperf	2.7.2	http://www.gnu.org/software/gperf/
    - gperf  # [unix]
    # gawk	3.1.1	http://www.gnu.org/software/gawk/
    - gawk  # [unix]
    # m4	1.4.1	http://www.gnu.org/software/m4/
    - m4  # [unix]
    # make	3.79.1	http://www.gnu.org/software/make/
    - make  # [unix]
  host:
    # OpenSSL?	0.9.7i	http://www.openssl.org/
    - openssl
  run:
    # OpenSSL?	0.9.7i	http://www.openssl.org/
    - openssl


test:
  commands:
    # virtuoso-t, isql, isqlw, virt_mail, virtuoso-sample-t, inifile
    - isql --help

about:
  home: https://virtuoso.openlinksw.com
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: |
    Virtuoso is a high-performance and scalable Multi-Model RDBMS, Data
    Integration Middleware, Linked Data Deployment, and HTTP Application Server
    Platform
  doc_url: http://vos.openlinksw.com/owiki/wiki/VOS
  dev_url: https://github.com/openlink/virtuoso-opensource

extra:
  recipe-maintainers:
    - bollwyvl
